title: Mesh Omaha
description: Meshtastic in the greater Omaha metro
theme: minima

# Optional nice-to-haves supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  # Header navigation links
  nav:
    - title: "Home"
      url: "/"
    - title: "Docs"
      url: "/docs/"
    - title: "Blog"
      url: "/blog/"
    - title: "About"
      url: "/about/"

author: "Scott Redd"
